using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class freeMovement : MonoBehaviour
{

    public float speed;

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.LeftArrow)){
            transform.position += (Vector3.left * (speed * Time.deltaTime));
        }
        
        if (Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.RightArrow)){
            transform.position += (Vector3.right * (speed * Time.deltaTime));
        }

        if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.UpArrow)){
            transform.position += (Vector3.up * (speed * Time.deltaTime));
        }
        
        if (Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.DownArrow)){
            transform.position += (Vector3.down * (speed * Time.deltaTime));
        }
    }
}
